name: Feature request
description: Suggest a protocol, operator, or reference client improvement.
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Protocol (spec/invariants)
        - Operator (policies/infra/docs)
        - Reference client (UI/API)
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
